apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deploy
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - image: registry0mu5980.azurecr.io/poi:latest
          imagePullPolicy: IfNotPresent
          name: poi
          livenessProbe:
            httpGet:
              path: /api/poi/healthcheck
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/poi/healthcheck
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONFIG_FILES_PATH
              value: /kvmnt
            - name: SQL_USER
              value: sqladmin0Mu5980
            # - name: SQL_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: kvcreds
            #       key: openhack-sqlserver-password
            - name: SQL_SERVER
              value: sqlserver0mu5980.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          volumeMounts:
            - name: kv-volume
              mountPath: /kvmnt
              readOnly: true
      volumes:
        - name : kv-volume
          flexVolume:
            driver: "azure/kv"
            secretRef:
              name: kvcreds                             # [OPTIONAL] not required if using Pod Identity
            options:
              keyvaultname: "openhack-table7"              # [REQUIRED] the name of the KeyVault
              keyvaultobjectnames: "openhack-sqlserver-password"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
              keyvaultobjectaliases: SQL_PASSWORD
              keyvaultobjecttypes: secret               # [REQUIRED] list of KeyVault object types: secret, key, cert
              resourcegroup: "teamResources"        # [REQUIRED for version < v0.0.14] the resource group of the KeyVault
              subscriptionid: "78f223ec-094a-44f0-89f1-d30dcfff5eb6"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
              tenantid: "e0a8d5d6-9574-40df-a69d-bd3f3e6029c2"                    # [REQUIRED] the tenant ID of the KeyVaul