apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deploy
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - image: registry0mu5980.azurecr.io/poi:latest
          imagePullPolicy: IfNotPresent
          name: poi
          livenessProbe:
            httpGet:
              path: /api/poi/healthcheck
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/poi/healthcheck
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SQL_USER
              value: sqladmin0Mu5980
            - name: SQL_PASSWORD
              value: gK79w4F79
            - name: SQL_SERVER
              value: sqlserver0mu5980.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
