apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deploy
  labels:
    deploy: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - image: registry0mu5980.azurecr.io/tripviewer:latest
          imagePullPolicy: IfNotPresent
          name: tripviewer
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile-svc:80
            - name: TRIPS_API_ENDPOINT
              value: http://trips-svc:80
