apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"addon-http-application-routing-external-dns","kubernetes.io/cluster-service":"true"},"name":"addon-http-application-routing-external-dns","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"addon-http-application-routing-external-dns"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"checksum/cloud-provider-config":"5108221c3093dbee00788600eb80ee924a6283edfeb0e7e999c994eac69bf43c"},"labels":{"app":"addon-http-application-routing-external-dns"}},"spec":{"containers":[{"args":["--source=service","--source=ingress","--provider=azure","--azure-resource-group=MC_teamResources_aksopenhack_northeurope","--domain-filter=5ee1b44bc9ed407a9dc1.northeurope.aksapp.io","--annotation-filter=kubernetes.io/ingress.class=addon-http-application-routing","--interval=3m0s"],"image":"aksrepos.azurecr.io/mirror/external-dns:v0.4.8","imagePullPolicy":"IfNotPresent","name":"addon-http-application-routing-external-dns","volumeMounts":[{"mountPath":"/etc/kubernetes/azure.json","name":"azure-config-file","readOnly":true}]}],"imagePullSecrets":[{"name":"emptyacrsecret"}],"nodeSelector":{"beta.kubernetes.io/os":"linux"},"priorityClassName":"system-node-critical","serviceAccountName":"addon-http-application-routing-external-dns","tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/etc/kubernetes/azure.json"},"name":"azure-config-file"}]}}}}
  creationTimestamp: "2020-01-22T11:28:41Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: addon-http-application-routing-external-dns
    kubernetes.io/cluster-service: "true"
  name: addon-http-application-routing-external-dns
  namespace: kube-system
  resourceVersion: "138252"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/addon-http-application-routing-external-dns
  uid: 57afd5e2-3d0a-11ea-a57b-76a9e6679ca7
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: addon-http-application-routing-external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/cloud-provider-config: 5108221c3093dbee00788600eb80ee924a6283edfeb0e7e999c994eac69bf43c
      creationTimestamp: null
      labels:
        app: addon-http-application-routing-external-dns
    spec:
      containers:
      - args:
        - --source=service
        - --source=ingress
        - --provider=azure
        - --azure-resource-group=MC_teamResources_aksopenhack_northeurope
        - --domain-filter=5ee1b44bc9ed407a9dc1.northeurope.aksapp.io
        - --annotation-filter=kubernetes.io/ingress.class=addon-http-application-routing
        - --interval=3m0s
        image: aksrepos.azurecr.io/mirror/external-dns:v0.4.8
        imagePullPolicy: IfNotPresent
        name: addon-http-application-routing-external-dns
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/azure.json
          name: azure-config-file
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: emptyacrsecret
      nodeSelector:
        beta.kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: addon-http-application-routing-external-dns
      serviceAccountName: addon-http-application-routing-external-dns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/kubernetes/azure.json
          type: ""
        name: azure-config-file
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-22T11:28:49Z"
    lastUpdateTime: "2020-01-22T11:28:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
