apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"addon-http-application-routing-default-http-backend","kubernetes.io/cluster-service":"true"},"name":"addon-http-application-routing-default-http-backend","namespace":"kube-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"addon-http-application-routing-default-http-backend"}},"template":{"metadata":{"labels":{"app":"addon-http-application-routing-default-http-backend"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"labelSelector":null,"matchExpressions":[{"key":"kubernetes.azure.com/cluster","operator":"Exists"}]}]}}},"containers":[{"image":"aksrepos.azurecr.io/mirror/defaultbackend:1.4","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthz","port":8080,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":5},"name":"addon-http-application-routing-default-http-backend","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"10m","memory":"20Mi"},"requests":{"cpu":"10m","memory":"20Mi"}}}],"imagePullSecrets":[{"name":"emptyacrsecret"}],"nodeSelector":{"beta.kubernetes.io/os":"linux"},"priorityClassName":"system-node-critical","terminationGracePeriodSeconds":60,"tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"}]}}}}
  creationTimestamp: "2020-01-22T11:28:41Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: addon-http-application-routing-default-http-backend
    kubernetes.io/cluster-service: "true"
  name: addon-http-application-routing-default-http-backend
  namespace: kube-system
  resourceVersion: "138257"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/addon-http-application-routing-default-http-backend
  uid: 57b960d6-3d0a-11ea-a57b-76a9e6679ca7
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: addon-http-application-routing-default-http-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: addon-http-application-routing-default-http-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
      containers:
      - image: aksrepos.azurecr.io/mirror/defaultbackend:1.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: addon-http-application-routing-default-http-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: emptyacrsecret
      nodeSelector:
        beta.kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-22T11:28:41Z"
    lastUpdateTime: "2020-01-22T11:28:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
