version: '3'
services:
  tripinsights/poi:1.0:
    build: .
    ports:
    - "8080:"
    environment:
    - SQL_PASSWORD: development
    - SQL_SERVER: 'true'
    - ASPNETCORE_ENVIRONMENT: 'production'   

    links:
    - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest