apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    deploy: userprofilejava
  name: userprofilejava-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofilejava
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: userprofilejava
    spec:
      containers:
      - env:
        - name: CONFIG_FILES_PATH
          value: /kvmnt
        - name: SQL_USER
          value: sqladmin0Mu5980
        - name: SQL_SERVER
          value: sqlserver0mu5980.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        image: registry0mu5980.azurecr.io/userprofilejava:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/user-java/healthcheck
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        name: userprofilejava
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/user-java/healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
        volumeMounts:
        - mountPath: /kvmnt
          name: kv-volume
          readOnly: true
      volumes:
      - flexVolume:
          driver: azure/kv
          options:
            keyvaultname: openhack-table7
            keyvaultobjectaliases: SQL_PASSWORD
            keyvaultobjectnames: openhack-sqlserver-password
            keyvaultobjecttypes: secret
            resourcegroup: teamResources
            subscriptionid: 78f223ec-094a-44f0-89f1-d30dcfff5eb6
            tenantid: e0a8d5d6-9574-40df-a69d-bd3f3e6029c2
          secretRef:
            name: kvcreds
        name: kv-volume
status: {}