apiVersion: v1
kind: Service
metadata:
  name: "api-userprofilejava-svc"
spec:
  type: ClusterIP
  selector:
    app: userprofilejava
  ports:
    - protocol: TCP
      name: userprofilejava-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: userprofilejava-https
      port: 443
      targetPort: 443
