apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web-dev
  name: web-dev-user
rules:
- apiGroups: ["","extensions", "apps"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api-dev
  name: api-dev-user
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
