apiVersion: v1
kind: Service
metadata:
  name: "api-userprofile-svc"
spec:
  type: ClusterIP
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      name: userprofile-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: userprofile-https
      port: 443
      targetPort: 443
